### ISSUE TITLE
Add option to relay join part in tg group to IRC

### ISSUE THREAD

**Issue by acagastya** [FruitieX/teleirc#209] opened 2017-09-12 03:56 UTC
It would be helpful to have information about who joined or left the telegram group on IRC chatrooms. Could you please add that feature?

**Comment by Mikaela** [comment] 2017-09-12 08:10
Duplicate of https://github.com/FruitieX/teleirc/issues/193.

**Closed by Mikaela** 2017-09-12 08:10 UTC

**Comment by acagastya** [comment] 2017-09-12 08:14
@Mikaela this is different from #193. The bot should announce on IRC channel who joined the telegram group.

**Comment by Mikaela** [comment] 2017-09-12 09:18
> The bot should announce on IRC channel who joined the telegram group.

I see `username was added by username`, but in that case this would be a duplicate of https://github.com/FruitieX/teleirc/issues/72 ?
