### ISSUE TITLE
Telegram -> IRC message relaying stops

### ISSUE THREAD

**Issue by kengu2** [FruitieX/teleirc#41] opened 2016-01-21 18:19 UTC
After running teleirc for some days there have now been two occasions where the messages from Telegram are not passed on to IRC but works all the time the other way round. There is no sign of those messages in the debug.

After restart the missing messages are relayed from the queue.

**Comment by FruitieX** [comment] 2016-01-24 22:32
Very odd, I've been running mine for months now without problems. Which IRC network is this on, and can you confirm that you are running the latest version of teleirc (along with up to date libraries in node_modules)?

**Comment by kengu2** [comment] 2016-01-24 22:42
Network is Freenode. Teleirc is the latest and for the last 3 days it has been running without problems. Libraries should also be up to date as it is pretty fresh install. 

It might (but without any evidence) be related to either attachments or possibly reconnecting on IRC network.

**Comment by FruitieX** [comment] 2016-02-04 14:49
Hey, I haven't been able to reproduce this problem unfortunately. Sorry about the delay also, I'm on a very busy schedule at the moment. I'd very much like to fix this, so if you have logs can you check if:

* The message "  >> relaying to IRC: _____" is still printed to console when a message was supposed to be relayed to IRC.
* Has the IRC module raised any errors for some reason? (grep the logs for the string "IRC ERROR") Currently there's no auto-reconnect on error, but maybe there should be.

I'll have to do some more thorough tests with e.g. disconnecting my network connection and checking if teleirc continues working.

**Comment by kengu2** [comment] 2016-02-11 20:08
To reproduce this problem seems a bit tricky. As there seems not to be any obvious reasons. Now when there is another channel added we found out that the relaying can stop on one channel but continue on the other.

There is no sign in the logs of the messages that are not relayed. So no log stating "relaying to IRC". And the error on IRC side. It is still on both channels and relaying in one direction on both channels.

This is what there is then on restart of teleirc. It relays the missing messages. Some lines are here multiple times but not shown on IRC. (id's of channels I obfuscated a bit)

```
$ teleirc


NOTE!
=====
id found for: Vaasa Hacklab : -4169179
id found for: Hacklab.fi : -10830927


11 Feb 15:00:52 - Sending irc NICK/USER
  >> relaying to IRC: <oh6gzt>: Ku ny sais aikaiseksi
11 Feb 15:00:53 - SEND: NICK vhtg
11 Feb 15:00:54 - SEND: USER bot 8 * :Telegram IRC Bot
  >> relaying to IRC: <oh6gzt>: Ku ny sais aikaiseksi
  >> relaying to IRC: <oh6gzt>: Ku ny sais aikaiseksi
  >> relaying to IRC: <oh6gzt>: Ku ny sais aikaiseksi
  >> relaying to IRC: <oh6gzt>: Ku ny sais aikaiseksi
11 Feb 15:01:02 - Unhandled message: { prefix: 'wolfe.freenode.net',
  server: 'wolfe.freenode.net',
  command: 'rpl_luserunknown',
  rawCommand: '253',
  commandType: 'reply',
  args: [ 'vhtg', '7', 'unknown connection(s)' ] }
11 Feb 15:01:02 - MODE: vhtg sets mode: +i
11 Feb 15:01:02 - SEND: JOIN #VaasaHacklab
11 Feb 15:01:03 - SEND: JOIN #hacklab.fi
  >> relaying to IRC: <oh6gzt>: Ku ny sais aikaiseksi
  >> relaying to IRC: <oh6gzt>: �
  >> relaying to IRC: <oh6gzt>: Sorville sähköä ja valoa. Sorvi itsessään odottaa jalkoja mutta jätän sen muille
  >> relaying to IRC: <oh6gzt>: Ping
11 Feb 15:01:05 - SEND: PRIVMSG #VaasaHacklab :<oh6gzt>: Ku ny sais aikaiseksi
  >> relaying to IRC: <oh6gzt>: (Photo, 1280x960) http://offshore.vaasa.hacklab.fi:9090/file_123.jpg
  >> relaying to IRC: <oh6gzt>: (Photo, 1280x960) http://offshore.vaasa.hacklab.fi:9090/file_124.jpg
11 Feb 15:01:06 - SEND: PRIVMSG #VaasaHacklab :<oh6gzt>: �
11 Feb 15:01:07 - SEND: PRIVMSG #VaasaHacklab :<oh6gzt>: Sorville sähköä ja valoa. Sorvi itsessään odottaa jalkoja mutta jätän sen muille
11 Feb 15:01:08 - SEND: PRIVMSG #VaasaHacklab :<oh6gzt>: Ping
11 Feb 15:01:09 - SEND: PRIVMSG #VaasaHacklab :<oh6gzt>: (Photo, 1280x960) http://offshore.vaasa.hacklab.fi:9090/file_123.jpg
11 Feb 15:01:10 - SEND: PRIVMSG #VaasaHacklab :<oh6gzt>: (Photo, 1280x960) http://offshore.vaasa.hacklab.fi:9090/file_124.jpg
11 Feb 15:01:11 - SEND: MODE #VaasaHacklab
11 Feb 15:01:12 - SEND: MODE #hacklab.fi

```

**Comment by lagleki** [comment] 2016-02-12 07:16
I confirm the same issue. It might be connected with periodic freenode network downtimes but I'm not that sure.

Seems that some forks of node-irc library support pinging so maybe try using them instead?
https://github.com/martynsmith/node-irc/pull/418

**Comment by lagleki** [comment] 2016-02-12 07:27
A similar Slack / IRC gateway seems to be free of that error: https://github.com/fntsrlike/slack-irc-syncbot (possibly via https://github.com/lagleki/slack-irc-syncbot/blob/master/lib/app.js#L80 haven't checked yet.)

**Comment by lagleki** [comment] 2016-02-12 08:58
Oh well, this app https://github.com/warbaque/tg_irc uses martyn smith's lib i just mentioned. maybe first try it and in case it never stops port the solution here

**Comment by FruitieX** [comment] 2016-02-15 17:23
@kengu2 can you test the [irc-git](https://github.com/FruitieX/teleirc/tree/irc-git) branch, which installs the node-irc module from latest master. Let me know if it works. If it fixes the issue, I'll release a hotfix version as soon as node-irc updates their npm module.

**Comment by kengu2** [comment] 2016-02-20 22:05
I can try (or running at the moment) but as the problem is pretty random it might be difficult to figure out if the problem persists or if it is fixed. 

Interesting thing to note is that when the bot is on two channels the relaying stopped on one but it continued on other a week ago.

**Comment by FruitieX** [comment] 2016-02-23 00:31
*That's* odd for sure. Let's hope that the latest node-irc module fixes the problem, report back if you notice that it doesn't.

**Comment by kengu2** [comment] 2016-02-23 07:07
During the night teleirc had some weird functionality. As there are other connections from the specific host to freenode without problems and teleirc had connections to different servers randomly I don't think the problem is with freenode as such.

Disconnecting from IRC every 4-5 minutes
Messaging telegram on every connect "topic for channel undefined"
Each IRC message seemed to be relayed twice to telegram

```
CyclingPingTimer 20: server silent for too long, let's send a PING
23 Feb 01:27:37 - SEND: PING 12394
23 Feb 01:27:48 - SEND: PONG asimov.freenode.net
CyclingPingTimer 20: server silent for too long, let's send a PING
23 Feb 01:28:03 - SEND: PING 12395
CyclingPingTimer 20: server silent for too long, let's send a PING
23 Feb 01:28:19 - SEND: PING 12396
CyclingPingTimer 20: server silent for too long, let's send a PING
23 Feb 01:28:35 - SEND: PING 12397
CyclingPingTimer 20: server silent for too long, let's send a PING
23 Feb 01:28:51 - SEND: PING 12398
CyclingPingTimer 20: server silent for too long, let's send a PING
23 Feb 01:29:07 - SEND: PING 12399
CyclingPingTimer 20: server silent for too long, let's send a PING
23 Feb 01:29:23 - SEND: PING 12400
CyclingPingTimer 20: server silent for too long, let's send a PING
23 Feb 01:29:39 - SEND: PING 12401
23 Feb 01:29:51 - QUIT: vhtg10!~bot@sa.hacklab.fi Ping timeout: 244 seconds
23 Feb 01:29:51 - Unhandled message: { command: 'ERROR',
  rawCommand: 'ERROR',
  commandType: 'normal',
  args: [ 'Closing Link: sa.hacklab.fi (Ping timeout: 244 seconds)' 
] }
23 Feb 01:29:51 - Connection got "end" event  
23 Feb 01:29:51 - Connection got "close" event
23 Feb 01:29:51 - Disconnected: reconnecting
23 Feb 01:29:51 - Waiting 2000ms before retrying
23 Feb 01:29:52 - QUIT: vhtg10!~bot@sa.hacklab.fi Ping timeout: 244 seconds
23 Feb 01:29:54 - Sending irc NICK/USER  
23 Feb 01:29:54 - SEND: NICK vhtg
23 Feb 01:29:55 - SEND: USER bot 8 * :Telegram IRC Bot
23 Feb 01:29:56 - SEND: NICK vhtg11
...

...
CyclingPingTimer 22: server silent for too long, let's send a PING
23 Feb 01:34:40 - SEND: PING 12416
  >> relaying to TG: <oh>: jaa :)
  >> relaying to TG: <oh>: jaa :)


```
(different timezone on server)

![teleirc_flood](https://cloud.githubusercontent.com/assets/1246601/13243899/e2dc4a84-da0a-11e5-95f0-c7d9cfaccecc.png)

**Comment by lagleki** [comment] 2016-02-23 07:43
I confirm this "topic for channel undefined" so that i had to manually
patch the app to prevent this string from being sent.

What is more at some point messages to Telegram started duplicating itself
so that the every message was sent twice. Restarting the app fixed that
issue. Not sure for how long.


2016-02-23 10:07 GMT+03:00 kengu2 <notifications@github.com>:

**Comment by FruitieX** [comment] 2016-02-23 12:43
Ouch, something is seriously wrong there...

**Comment by lagleki** [comment] 2016-02-24 06:28
> What is more at some point messages to Telegram started duplicating itself
so that the every message was sent twice. Restarting the app fixed that
issue. Not sure for how long.

And in fact the reason for that is very simple. At some point the bot starts a second instance of itself. So if you have "telegrambot" as the IRC name of your bot it then creates "telegrambot1", "telegrambot2"  (at this point it stopped) which ultimately leads to all messages sent to Telegram several times.

Interesting that before this "node-irc" fix it never happened to me.

**Comment by lagleki** [comment] 2016-02-24 08:54
And a similar app for Slack/IRC gateway never shows such problems despite that it uses "irc": "~0.3.6":

https://github.com/fntsrlike/slack-irc-syncbot/blob/master/package.json#L28

**Comment by kengu2** [comment] 2016-02-26 10:55
Had to revert back to before "node-irc" version because of the connection flooding. Jumping on and off IRC network without reason and flooding IRC. And when connecting also stating the topic every time on telegram thus flooding Telegram.

**Comment by FruitieX** [comment] 2016-02-26 12:29
*sigh* time to write our own irc module? :p

**Comment by GeneralUnRest** [comment] 2016-02-28 04:46
I just ran into this issue. resetting it wasn't doing anything.
ended up just disabling serve media option and it started working again.

**Comment by FruitieX** [comment] 2016-02-29 08:31
That option *should* be unrelated to this problem @GeneralUnRest. I believe the problem lies in the IRC module. We're setting up the event listeners once ([here](https://github.com/FruitieX/teleirc/blob/develop/irc.js#L29-L90)), so I'm not sure how they can start firing multiple times unless that module is broken.

It is of course a possibility that the TG module is causing problems, but the problem @lagleki described supports the theory of the IRC module being broken since it connected to the IRC network multiple times (taking up several nicks).

I have one theory of what happened on your end @kengu2: maybe the connection between your server and the IRC network was down for an extended amount of time, causing lots of ping timeouts and reconnects in the IRC module. I'm trying to study how the module reacts to this situation, and to me it would seem that they never explicitly close a socket that was determined to have timed out? ([here](https://github.com/martynsmith/node-irc/blob/master/lib/irc.js#L858-L888)). They do manually trigger the 'close' event on the socket, but this AFAIK accomplishes nothing on node's side and they should also call [.destroy()](https://nodejs.org/api/net.html#net_socket_destroy) on the socket. It may be possible that the socket lingers around after their ping timeouts thus causing the problem.

This *could* explain why a message is relayed to IRC multiple times, but not really the other way around since it seems they really *do* remove the on 'data' event handler in either case. That is a little bit mysterious. Anyway, I wonder if it would help to add a `self.conn.destroy()` on [this line](https://github.com/martynsmith/node-irc/blob/master/lib/irc.js#L869).

**Comment by FruitieX** [comment] 2016-02-29 08:51
This `self.conn.destroy()` patch has been applied to https://github.com/FruitieX/teleirc/tree/irc-git

**Comment by jirwin** [comment] 2016-03-10 09:07
@FruitieX Just wanted to let you know that I've pushed a patch that seems to fix this @ https://github.com/martynsmith/node-irc/pull/452. It'd be great if you could give it a try as well so I can get it merged and finally publish the ping timeout support.

You were on the right track with `self.conn.destroy()`. The problem was because the code was emitting the `close` event on the socket directly instead of closing the connection and letting node emit the event itself.

Sorry for the trouble. Hope to get this fixed quickly.

**Comment by duck57** [comment] 2016-03-24 20:53
I'm not sure if I should open a new issue for this or not, but I'm having a related but opposite problem. IRC messages for a specific channel aren't getting relayed to Telegram. In fact, there is nothing in the console output to show that the bot attempted to post to Telegram—it's like he bot has write access to the one channel but can't read from it. 

However, this only is happening for one of the two links I made. On the other channel, it's working normally. It does not depend on which order I list the links in config.js, either. I'll play around with debug mode for a bit and let you know if I find anything else interesting.

**Comment by duck57** [comment] 2016-03-24 21:17
It turns out that the IRC channel name is case-sensitive for reading, but the server I connected to is not case-sensitive, so it will forward messages to #CHANNEL to #channel.

**Comment by Mikaela** [comment] 2016-03-25 06:46
> It turns out that the IRC channel name is case-sensitive for reading, but the server I connected to is not case-sensitive, so it will forward messages to #CHANNEL to #channel.

This sounds like https://github.com/FruitieX/teleirc/issues/36.

**Comment by duck57** [comment] 2016-03-25 21:27
It seems to be exactly #36.

**Comment by jirwin** [comment] 2016-03-26 19:26
@FruitieX Just letting you know that I've published node-irc 0.5.0 that has the fix for this in it.

**Comment by FruitieX** [comment] 2016-03-26 20:01
Thank you very much for the note @jirwin, I will work towards a new hotfix release for next week when I'm finished with holidays. :)

**Comment by lagleki** [comment] 2016-03-27 07:14
Very strange but I just started getting another error when running the app:
```
IRC ERROR:
{ prefix: 'verne.freenode.net',
  server: 'verne.freenode.net',
  command: 'err_nosuchserver',
  rawCommand: '402',
  commandType: 'error',
  args: [ 'BOTNAME', 'irc.freenode.net', 'No such server' ] }
```

where instead of BOTNAME there is the name of my bot. I'm not sure if it's related to freenode network only.
Messages from IRC to Telegram are still comng.

**Comment by FruitieX** [comment] 2016-04-08 13:46
Right, so this should be fixed now. Let me know if this is not the case, otherwise we're releasing 0.4.5 by the end of next week!

**Closed** 2016-04-19 19:53 UTC
Labels: bug, feedback needed
