### ISSUE TITLE
I can't find out how to create ~/.teleirc/chat_ids

### ISSUE THREAD

**Issue by leoboiko** [FruitieX/teleirc#45] opened 2016-02-16 12:28 UTC
On console:

    ~/.teleirc/chat_ids file not found!

    Please add your Telegram bot to a Telegram group and have
    someone send a message to that group.
    teleirc will then automatically store your group chat_id.

On the Telegram group, after inviting bot as `teleirc_si_bot`:

    @teleirc_si_bot hi
    hi @teleirc_si_bot
    hi
    /names@teleirc_si_bot

No response.

If I write on IRC:

    >> relaying to TG: <leoboiko>: hi
    >> relaying to IRC: ERROR: No chat_id set! Add me to a Telegram group and say hi so I can find your group's chat_id!
    ERROR: No chat_id set! Add me to a Telegram group and say hi so I can find your group's chat_id!

I installed teleirc via npm for debian wheezy.

**Comment by FruitieX** [comment] 2016-02-16 12:32
Hello. Just some quick things I can come to think of from the README:

1. Did you remember to use the `/setprivacy` command with BotFather to allow the bot to see all Telegram messages?
2. Did you put your Telegram Bot API token into `~/.teleirc/config.js`?

**Comment by leoboiko** [comment] 2016-02-16 12:35
Yes, and yes:

    Enable' - your bot will only receive messages that either start with the '/' symbol or mention the bot by username.
    'Disable' - your bot will receive all messages that people send to groups.
    Current status is: DISABLED

I also tested the API token via wget, seems to be working.

(Incidentally, this isn't the place for this, but it took me a while to find out that the Botfather only understands bot names preceded by '@'; and that the "Disable" command is case-sensitive...)

**Comment by FruitieX** [comment] 2016-02-16 12:40
Weird. Something is stopping communication between the bot and the Telegram servers. Hmm, also, you did invite the bot via private chat with it -> click on name -> menu -> add to group? Just checking as there's this new inline bot feature - that doesn't work.

**Comment by leoboiko** [comment] 2016-02-16 12:45
I had clicked the group name, then "add member", on the web interface.  Now I tried from the bot's private chat, and still no results.

I just noticed that `getUpdates` return an empty list for the API token.  `getMe` does return the username correctly.

**Comment by FruitieX** [comment] 2016-02-16 12:52
In the web interface, I don't have an option of adding a bot via group name -> add member (it only lists Telegram contacts for me, no bots). I have to do that by selecting the bot from my contacts (first open a chat via the link BotFather gave me when creating the bot), then click on bot name -> add to group.

Either way if you did manage to correctly add the bot to your group (please still double check :smiley:), it's starting to sound like an issue on Telegram's side if calling the API manually doesn't work either...

**Comment by FruitieX** [comment] 2016-02-16 12:55
BTW I clarified the usage of `/setprivacy` command a little in 13aeff1de3dae49b9b925c98f69874cae70951a4, it was indeed a little dodgy.

**Comment by leoboiko** [comment] 2016-02-16 12:55
When it lists the human Telegram contacts, if I type the bot name, it *then* lists the bot.  At any rate the result seems to be the same; it says `leoboiko invited teleirc_si_bot` on the group chat; and then the bot is listed on the left panel.

I'll delete the bot and try everything again, who knows...

**Comment by FruitieX** [comment] 2016-02-16 12:57
Ah, I didn't know that, useful! Yeah, try at least generating a new API key and use that, this is sounding really odd...

**Comment by leoboiko** [comment] 2016-02-16 13:06
No luck; same behavior with a brand new bot.  Maybe I'm missing something obvious, or else it's something on Telegram's side...

**Comment by Xylix** [comment] 2016-02-17 14:54
Did you get it solved?

**Comment by leoboiko** [comment] 2016-02-17 14:56
No, sorry, I'm at my wit's and the bot just doesn't seem to respond to messages.  Feel free to close this report if you think the problem is unrelated to teleirc itself.

**Comment by Xylix** [comment] 2016-02-17 14:59
No I have the exactly same issue.

**Comment by FruitieX** [comment] 2016-02-18 01:18
Huh, maybe this is an issue with teleirc then. Is @Xylix also using the version from npm, or have you built it from git? Are you able to test running any other Telegram bot - that could really narrow it down to teleirc then if another bot does work. I can't really think of a reason why that should be though... 

Also if you guys have got time to debug some more, can you test running a build from latest `develop` branch in git? There's instructions at the bottom of the `README` on how to set teleirc up from git.

Let's keep this issue open, I definitely am interested in what the cause may be, will investigate more during the weekend when I hopefully have more time! :)

**Comment by Xylix** [comment] 2016-02-18 10:14
It was installed with npm-install.

**Comment by FruitieX** [comment] 2016-04-03 08:29
Looks like I did not have time. ;p

Any progress on this?

**Comment by zertrin** [comment] 2016-04-24 12:16
I think I had a similar problem some time ago, when trying to setup a second bot for teleirc to be run alongside the first one.

For some reason I never understood, I couldn't get it to work (it never received updates from Telegram), even though I followed the exact same steps as for the first one.

I eventually gave up and used the first bot with more chan-group pairs because that one was working.

Sorry for the lack of information, I have no plan in trying again since the current situation works well enough for me, but still wanted to report that the two previous reporters may not be alone to have experienced a similar issue.

**Comment by FruitieX** [comment] 2016-05-07 04:59
The way chat IDs are stored has now changed to better support multiple teleirc instances running on the same machine. So at least the problem reported by @zetrin should be fixed.

**Comment by FruitieX** [comment] 2016-05-07 11:45
Closing for now. Let me know if this is still of an issue to someone.

**Closed by FruitieX** 2016-05-07 11:45 UTC
Labels: bug, feedback needed

**Comment by guoyunhe** [comment] 2016-12-28 12:32
I have the same problem and have no idea how to solve it.

**Comment by FruitieX** [comment] 2016-12-28 13:28
It's supposed to be auto generated.

**Comment by FruitieX** [comment] 2016-12-28 13:29
@guoyunhe please provide more info :)

**Comment by guoyunhe** [comment] 2016-12-28 17:21
I installed it on my openSUSE laptop with firewall (forbid all ports outside TCP/UDP).

teleirc can join irc channel #opensuse-cn with nickname opensuse_cn_bot. I also added opensuse_cn_irc_bot to the Telegram group chat [opensuse_cn](https://telegram.me/opensuse_cn).

When I send message in IRC channel #opensuse-cn, it replies:

> No chat_id set! Add me to a Telegram group and say hi so I can find your group's chat_id!

But when I type something in Telegram group, it won't add any chat ids. And here is no ~/.teleirc/chat_ids or other files generated.

**Comment by guoyunhe** [comment] 2016-12-28 17:44
Debug output when receiving messages from Telegram:

```
debug: got tg msg: 
{ message_id: 1459,
  from: 
   { id: 197472852,
     first_name: 'Grover',
     last_name: 'Chou',
     username: 'GroverChouT' },
  chat: 
   { id: -1001091730439,
     title: 'openSUSE 中文社群',
     username: 'opensuse_cn',
     type: 'supergroup' },
  date: 1482946981,
  sticker: 
   { width: 512,
     height: 280,
     emoji: '🙈',
     thumb: 
      { file_id: 'AAQFABN_hb8yAASaOaci_DaksJMfAAIC',
        file_size: 1492,
        width: 128,
        height: 70 },
     file_id: 'BQADBQADSwADJ0oTCs0SsvHyP_3gAg',
     file_size: 7810 } }
verbose: Telegram group not found in config: "openSUSE 中文社群", dropping message...
CyclingPingTimer 0: server silent for too long, let's send a PING
28 Dec 19:42:49 - SEND: PING 6
```

**Comment by guoyunhe** [comment] 2016-12-28 18:17
I solved my problem, it is just a naming confusion.

My Telegram group is called "openSUSE 中文" and the username is [opensuse_cn](https://telegram.me/opensuse_cn). In teleirc's config.js, I write 'opensuse_cn' as Telegram group name. However, it only reads the display name of group, rather than username.

Suggestion: check both group display name and username. Username or short URL of group can also be treated as identity of a chat. This could help users avoid some mistakes.

**Comment by esahakki** [comment] 2017-09-28 00:11
Bot does not feel to handle Telegram group name change quite well. ChatID does not change that often, but is it really needed to verify correct TG-group on received messages?

**Comment by Mikaela** [comment] 2017-10-05 16:04
> Bot does not handle Telegram group name change quite well. ChatID does not change that often, but is it really needed to verify correct TG-group on received messages?

Could you open a new issue if there isn't one already open yet? Sorry if you already did, I am behind my email by 500 messages and trying to read them all now.

**Comment by cerebrux** [comment] 2018-09-09 22:47
@guoyunhe Ι love it when I come and see that a solution like yours still works after two years !

So for anybody here that will see this after years (like I did). What @guoyunhe said is simple:

If your group name has a url name like 'GroupName' but the display is 'Group Name' you should use the 'Group Name' in the tgGroup:'Group Name'
