### ISSUE TITLE
Long Telegram messages are truncated on IRC

### ISSUE THREAD

**Issue by FruitieX** [FruitieX/teleirc#97] opened 2016-04-19 10:57 UTC
Very long Telegram messages will be truncated on IRC. Do we handle this by splitting the message up into multiple messages (might be issues with spamming IRC), or how should we handle this properly?

**Comment by richrd** [comment] 2017-03-15 14:40
Isn't this what the config option `messageSplit` is supposed to do? I have this problem where messages are split but some characters are left out where the split happens.

**Comment by richrd** [comment] 2017-05-21 11:53
What's the status of this? I don't seem to have this problem anymore. Not sure why.

**Comment by esahakki** [comment] 2017-09-28 00:56
messageSplit setting might be evaluated wrong, I'm missing equal of TG-username length of characters from first splitted line in Irssi.

**Comment by richrd** [comment] 2017-09-28 08:03
Yeah, same here actually.

**Comment by Mikaela** [comment] 2017-10-05 16:12
I think that this is fixed on the git version.

**Comment by Mikaela** [comment] 2017-10-05 16:16
Actually this is a duplicate of https://github.com/FruitieX/teleirc/issues/186 .

**Closed by Mikaela** 2017-10-05 16:16 UTC
Labels: bug
